import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoteeer",
    price: 200,
    inStock: false,
    isFavourite: false,
    rating: 1,
  },
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoteeer",
    price: 200,
    inStock: true,
    isFavourite: false,
    rating: 2,
  },
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoteeer",
    price: 300,
    inStock: false,
    isFavourite: false,
    rating: 3,
  },
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoteeer",
    price: 4040,
    inStock: true,
    isFavourite: false,
    rating: 4,
  },
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoteeer",
    price: 5000,
    inStock: true,
    isFavourite: false,
    rating: 5,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Falg",
    price: 1000,
    inStock: true,
    isFavourite: false,
    rating: 1,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Falg",
    price: 2000,
    inStock: false,
    isFavourite: false,
    rating: 2,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Falg",
    price: 3000,
    inStock: false,
    isFavourite: false,
    rating: 3,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Falg",
    price: 4000,
    inStock: true,
    isFavourite: false,
    rating: 4,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Falg",
    price: 6000,
    inStock: true,
    isFavourite: false,
    rating: 5,
  },
  {
    _id: uuid(),
    catagoryName: "scaleModel",
    title: "Psotefefeeer",
    price: 100,
    inStock: false,
    isFavourite: false,
    rating: 1,
  },
  {
    _id: uuid(),
    catagoryName: "scaleModel",
    title: "Psotefefeeer",
    price: 3000,
    inStock: false,
    isFavourite: false,
    rating: 2,
  },
  {
    _id: uuid(),
    catagoryName: "scaleModel",
    title: "Psotefefeeer",
    price: 4000,
    inStock: false,
    isFavourite: false,
    rating: 3,
  },
  {
    _id: uuid(),
    catagoryName: "scaleModel",
    title: "Psotefefeeer",
    price: 7000,
    inStock: true,
    isFavourite: false,
    rating: 4,
  },
  {
    _id: uuid(),
    catagoryName: "scaleModel",
    title: "Psotefefeeer",
    price: 8000,
    inStock: false,
    isFavourite: false,
    rating: 5,
  },
  {
    _id: uuid(),
    catagoryName: "wearable",
    title: "Psoteeer",
    price: 6000,
    inStock: true,
    isFavourite: false,
    rating: 1,
  },
  {
    _id: uuid(),
    catagoryName: "wearable",
    title: "Psoteeer",
    price: 600,
    inStock: false,
    isFavourite: false,
    rating: 2,
  },
  {
    _id: uuid(),
    catagoryName: "wearable",
    title: "Psoteeer",
    price: 5000,
    inStock: true,
    isFavourite: false,
    rating: 3,
  },
  {
    _id: uuid(),
    catagoryName: "wearable",
    title: "Psoteeer",
    price: 2000,
    inStock: false,
    isFavourite: false,
    rating: 4,
  },
  {
    _id: uuid(),
    catagoryName: "wearable",
    title: "Psoteeer",
    price: 6000,
    inStock: false,
    isFavourite: false,
    rating: 5,
  },
  {
    _id: uuid(),
    catagoryName: "poster",
    title: "Psoter",
    price: 3000,
    inStock: true,
    isFavourite: false,
    rating: 6,
  },
  {
    _id: uuid(),
    catagoryName: "flag",
    title: "Psoter",
    price: 3000,
    inStock: true,
    isFavourite: false,
    rating: 7,
  },
];
